"""
routers/tab2_variance.py  — FIXED
Fixes:
  1. GET /filters now falls back to final_db_bytes (Tab 1 output)
     so "Load Tab 1 Data" works without re-uploading
  2. _load_master() checks both session keys: master_db_bytes → final_db_bytes
  3. _safe_records() uses iloc (no itertuples) — safe for any column names
  4. NaN / inf sanitised before JSONResponse
  5. run endpoint: NaN in delta_pct (div-by-zero) sanitised before response
"""
from __future__ import annotations

import io
import math
import uuid

import numpy as np
import pandas as pd
from fastapi import APIRouter, File, Form, HTTPException, Request, UploadFile
from fastapi.responses import JSONResponse, StreamingResponse

from services import data_helpers as dh
from services import session_store as ss
from services.excel_export import build_excel_export

router = APIRouter()


def _sid(request: Request) -> str:
    return request.cookies.get("va_sid", str(uuid.uuid4()))


# ── Safe serialisation helpers ────────────────────────────────────────────

def _safe_val(v):
    """NaN / inf / numpy scalars → JSON-safe Python types."""
    if v is None:
        return None
    if isinstance(v, float):
        if math.isnan(v) or math.isinf(v):
            return None
        return v
    try:
        import numpy as np
        if isinstance(v, (np.floating,)):
            f = float(v)
            return None if (math.isnan(f) or math.isinf(f)) else f
        if isinstance(v, (np.integer,)):
            return int(v)
        if isinstance(v, np.bool_):
            return bool(v)
    except ImportError:
        pass
    return v


def _safe_records(df: pd.DataFrame) -> list:
    """
    iloc-based serialisation — safe for column names with spaces/special chars.
    Never uses itertuples() which mangles column names.
    """
    cols = df.columns.tolist()
    result = []
    for i in range(len(df)):
        row_dict = {}
        for j, col in enumerate(cols):
            row_dict[col] = _safe_val(df.iloc[i, j])
        result.append(row_dict)
    return result


def _sanitise_df(df: pd.DataFrame) -> pd.DataFrame:
    """Replace NaN/inf in float columns; NaN in object columns → empty string."""
    df = df.copy()
    for col in df.select_dtypes(include=["float", "float64", "float32"]).columns:
        df[col] = df[col].apply(
            lambda x: None if (x is None or (isinstance(x, float)
                               and (math.isnan(x) or math.isinf(x)))) else x
        )
    for col in df.select_dtypes(include=["object"]).columns:
        df[col] = df[col].apply(
            lambda x: "" if (x is None or (isinstance(x, float)
                             and math.isnan(x))) else x
        )
    return df


# ── Session helpers ───────────────────────────────────────────────────────

def _store_master(sid: str, df: pd.DataFrame) -> None:
    ss.set(sid, "master_db_bytes", df.to_json(orient="split"))


def _load_master(sid: str) -> pd.DataFrame:
    """
    FIX: Try master_db_bytes first (uploaded via Tab 2),
    then fall back to final_db_bytes (generated by Tab 1 mapping).
    This is why 'Load Tab 1 Data' was failing — it stored under
    final_db_bytes but Tab 2 only looked for master_db_bytes.
    """
    raw = ss.get(sid, "master_db_bytes")
    if raw is None:
        # Fall back to Tab 1 output
        raw = ss.get(sid, "final_db_bytes")
    if raw is None:
        raise HTTPException(
            404,
            "No data in session. "
            "Either run Tagetik Mapping (Tab 1) first, or upload a file here."
        )
    return pd.read_json(io.StringIO(raw), orient="split")


def _set_cookie(resp, sid: str):
    resp.set_cookie("va_sid", sid, httponly=True, samesite="lax")
    return resp


# ── POST /api/tab2/upload ─────────────────────────────────────────────────

@router.post("/upload")
async def upload_master(request: Request, file: UploadFile = File(...)):
    sid = _sid(request)
    file_bytes = await file.read()
    try:
        df = dh.read_and_normalise(file_bytes)
    except Exception as exc:
        raise HTTPException(422, str(exc))

    if "Scenario" not in df.columns:
        raise HTTPException(422, "File must contain a 'Scenario' column.")

    _store_master(sid, df)
    opts = dh.get_filter_options(df)
    resp = JSONResponse({
        "session_id": sid,
        "rows":       len(df),
        "columns":    df.columns.tolist(),
        **opts,
    })
    return _set_cookie(resp, sid)


# ── POST /api/tab2/upload-two ─────────────────────────────────────────────

@router.post("/upload-two")
async def upload_two(
    request: Request,
    file_a:  UploadFile = File(...),
    file_b:  UploadFile = File(...),
    label_a: str = Form("Scenario_A"),
    label_b: str = Form("Scenario_B"),
):
    sid = _sid(request)
    try:
        dfa = dh.read_and_normalise(await file_a.read()).copy()
        dfb = dh.read_and_normalise(await file_b.read()).copy()
    except Exception as exc:
        raise HTTPException(422, str(exc))

    dfa["Scenario"] = label_a.strip() or "Scenario_A"
    dfb["Scenario"] = label_b.strip() or "Scenario_B"
    common = list(set(dfa.columns) & set(dfb.columns))
    df = pd.concat([dfa[common], dfb[common]], ignore_index=True)

    _store_master(sid, df)
    opts = dh.get_filter_options(df)
    resp = JSONResponse({
        "session_id": sid,
        "rows":       len(df),
        "columns":    df.columns.tolist(),
        **opts,
    })
    return _set_cookie(resp, sid)


# ── GET /api/tab2/filters ─────────────────────────────────────────────────

@router.get("/filters")
async def get_filters(request: Request):
    """
    FIX: _load_master now falls back to final_db_bytes (Tab 1 output),
    so this endpoint works after Tab 1 mapping without re-uploading.
    """
    sid = _sid(request)
    df  = _load_master(sid)   # ← now checks both session keys
    return JSONResponse(dh.get_filter_options(df))


# ── POST /api/tab2/load-tab1 ─────────────────────────────────────────────
# NEW dedicated endpoint called by "Load Tab 1 Data" button in JS

@router.post("/load-tab1")
async def load_tab1(request: Request):
    """
    Explicitly promote Tab 1 final_db_bytes → master_db_bytes
    so all Tab 2 operations (run, download) use the same key.
    """
    sid = _sid(request)
    raw = ss.get(sid, "final_db_bytes")
    if raw is None:
        raise HTTPException(
            404,
            "No Tab 1 mapping data found. "
            "Go to the Tagetik Mapping tab, upload your file and click Generate Mapping first."
        )

    df = pd.read_json(io.StringIO(raw), orient="split")

    # Tab 1 output may not have a Scenario column — that is fine,
    # the user will pick scenarios from whatever columns exist.
    _store_master(sid, df)

    opts = dh.get_filter_options(df)
    resp = JSONResponse({
        "session_id": sid,
        "rows":       len(df),
        "columns":    df.columns.tolist(),
        "source":     "tab1",
        **opts,
    })
    return _set_cookie(resp, sid)


# ── POST /api/tab2/run ────────────────────────────────────────────────────

@router.post("/run")
async def run_variance(request: Request):
    sid  = _sid(request)
    df   = _load_master(sid)
    body = await request.json()

    scenario_a         = body.get("scenario_a", "")
    scenario_b         = body.get("scenario_b", "")
    sel_period         = body.get("sel_period", "")
    group_fields       = body.get("group_fields", [])
    favorable_is_lower = body.get("favorable_is_lower", True)
    sel_markets        = body.get("sel_markets", [])
    sel_regions        = body.get("sel_regions", [])
    sel_divisions      = body.get("sel_divisions", [])
    sel_entities       = body.get("sel_entities", [])
    sel_lc_oh          = body.get("sel_lc_oh", [])

    if not group_fields:
        raise HTTPException(422, "group_fields must not be empty.")
    if not scenario_a or not scenario_b:
        raise HTTPException(422, "scenario_a and scenario_b are required.")

    month_cols = dh.get_month_cols(df)
    if (sel_period != "__YTD_CALC__"
            and sel_period not in df.columns
            and sel_period != "YTD"):
        raise HTTPException(422, f"Period column '{sel_period}' not found in data.")

    try:
        df_filtered = dh.apply_filters(
            df, scenario_a, scenario_b,
            sel_markets, sel_regions,
            sel_divisions, sel_entities, sel_lc_oh,
        )
        leaf_df, pivot_source_long, period_label = dh.run_variance(
            df_filtered, group_fields,
            scenario_a, scenario_b, sel_period, month_cols,
        )
    except Exception as exc:
        raise HTTPException(500, str(exc))

    # ── Sanitise before storing and returning ────────────────────────────
    leaf_df = _sanitise_df(leaf_df)

    ss.set(sid, "leaf_df_bytes",   leaf_df.to_json(orient="split"))
    ss.set(sid, "pivot_src_bytes", pivot_source_long.to_json(orient="split"))
    ss.set(sid, "var_context", {
        "sel_period":        period_label,
        "scenario_a":        scenario_a,
        "scenario_b":        scenario_b,
        "header_a":          f"{scenario_a} (A)",
        "header_b":          f"{scenario_b} (B)",
        "group_fields":      group_fields,
        "favorable_is_lower": favorable_is_lower,
        "sel_markets":       sel_markets,
        "sel_regions":       sel_regions,
        "sel_divisions":     sel_divisions,
    })

    total_a   = float(leaf_df["A"].sum())
    total_b   = float(leaf_df["B"].sum())
    total_var = total_a - total_b
    pct_var   = (total_var / total_b * 100) if total_b != 0 else 0.0
    max_var_raw = leaf_df["delta"].abs().max()
    max_var   = 0.0 if (math.isnan(max_var_raw) or math.isinf(max_var_raw)) else float(max_var_raw)

    top5 = leaf_df.nsmallest(5, "delta") if favorable_is_lower else leaf_df.nlargest(5, "delta")
    bot5 = leaf_df.nlargest(5, "delta")  if favorable_is_lower else leaf_df.nsmallest(5, "delta")

    return JSONResponse({
        "period_label":       period_label,
        "total_a":            dh.fmt_num(total_a),
        "total_b":            dh.fmt_num(total_b),
        "total_variance":     dh.fmt_num(total_var),
        "pct_variance":       f"{pct_var:+.1f}%",
        "max_variance":       dh.fmt_num(max_var),
        "favorable_is_lower": favorable_is_lower,
        "rows":               len(leaf_df),
        "columns":            leaf_df.columns.tolist(),
        "records":            _safe_records(leaf_df),
        "top5":               _safe_records(top5),
        "bot5":               _safe_records(bot5),
        "hotspot":            _build_hotspot(leaf_df, group_fields, favorable_is_lower),
    })


# ── GET /api/tab2/download/xlsx ───────────────────────────────────────────

@router.get("/download/xlsx")
async def download_xlsx(request: Request):
    sid      = _sid(request)
    raw_leaf = ss.get(sid, "leaf_df_bytes")
    raw_src  = ss.get(sid, "pivot_src_bytes")
    ctx      = ss.get(sid, "var_context")

    if not raw_leaf or not ctx:
        raise HTTPException(404, "No variance result in session. Run analysis first.")

    leaf_df           = pd.read_json(io.StringIO(raw_leaf), orient="split")
    pivot_source_long = pd.read_json(io.StringIO(raw_src), orient="split") if raw_src else None

    excel_bytes = build_excel_export(
        leaf_df=leaf_df,
        group_fields=ctx["group_fields"],
        header_a=ctx["header_a"],
        header_b=ctx["header_b"],
        sel_period=ctx["sel_period"],
        sel_markets=ctx.get("sel_markets", []),
        sel_regions=ctx.get("sel_regions", []),
        sel_divisions=ctx.get("sel_divisions", []),
        scenario_a=ctx["scenario_a"],
        scenario_b=ctx["scenario_b"],
        favorable_is_lower=ctx["favorable_is_lower"],
        pivot_source_long=pivot_source_long,
    )

    safe_period = ctx["sel_period"].replace("/", "-")
    return StreamingResponse(
        io.BytesIO(excel_bytes),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f"attachment; filename=variance_report_{safe_period}.xlsx"},
    )


# ── Helpers ───────────────────────────────────────────────────────────────

def _build_hotspot(leaf_df: pd.DataFrame, group_fields: list, fav_lower: bool) -> list:
    if not group_fields or leaf_df.empty:
        return []
    last_dim = group_fields[-1]
    if last_dim not in leaf_df.columns:
        return []
    agg = (
        leaf_df.groupby(last_dim, dropna=False)
        .agg(A=("A", "sum"), B=("B", "sum"))
        .reset_index()
    )
    agg["delta"] = agg["A"] - agg["B"]
    agg["pct"]   = np.where(agg["B"] == 0, None,
                            (agg["delta"] / agg["B"]) * 100)
    sorted_agg = (
        agg.sort_values("delta", ascending=False)
        if fav_lower else
        agg.sort_values("delta", ascending=True)
    ).head(4)
    return _safe_records(_sanitise_df(sorted_agg.reset_index(drop=True)))
